directories:
  output: dist-electron
  buildResources: build
appId: com.quickbiza.pos
productName: QuickBiza
icon: frontend/public/Appicon.png
publish:
  provider: github
  owner: nyakoe
  repo: quickbiza-pos
files:
  - filter:
      - electron/**/*
      - backend/**/*
      - frontend/dist/**/*
      - package.json
extraResources:
  - from: backend
    to: backend
    filter:
      - '**/*'
      - '!*.log'
      - '!*.db*'
win:
  target: nsis
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
  shortcutName: QuickBiza POS
  uninstallDisplayName: QuickBiza POS
linux:
  target:
    - AppImage
    - deb
    - zip
  category: Office
electronVersion: 28.3.3
